### PR TITLE
Newstroke: Reduce height of curly braces

### LINKED ISSUE #6: Newstroke: Reduce height of curly braces
img

The curly braces look unbalanced. I think they should only be as high as the cap height.

### PR DESCRIPTION
**Pull request by dbrgn**
Fixes #6.

Before:

img

https://fontobene.dbrgn.ch/pathvis/#init=3,-3.43;2.57,-3.43;1.71,-3;1.29,-2.14;1.29,2.14;.86,3;0,3.43;.86,3.86;1.29,4.71;1.29,9;1.71,9.86;2.57,10.29;3,10.29

After:

img

https://fontobene.dbrgn.ch/pathvis/#init=3,0;2.57,0;1.71,.43;1.29,1.29;1.29,3.21;.86,4.07;0,4.5;.86,4.93;1.29,5.79;1.29,7.71;1.71,8.57;2.57,9;3,9

### CODE REVIEW

**Comment by ubruhin** [comment]
Hmm for me the braces look too small now because of letters which go below the baseline, for example the "p" (new height at left, old height at right):

grafik

When looking at other commonly used fonts (OTF/TTF), many seem to do something in between, for example Noto Sans:

grafik

As a compromise, I'd suggest to use a height in the middle between the old and the new height :)

Another thing: Should we really modify the "newstroke" font, which was 100% original until now? Or should we introduce our own font, as a fork of newstroke? In the long term we should make more changes anyway (especially by start using arcs) so the font drifts away from newstroke more and more... Maybe the original newstroke font is even useful some day for a KiCad to LibrePCB converter to ensure maximum compatibility ;)

**Comment by dbrgn** [comment]
I actually like the look with the cap height, but if you prefer I can adjust the lower Y coordinate as suggested.

> Another thing: Should we really modify the "newstroke" font, which was 100% original until now?

By converting it we have already kind of forked it. I don't really care, we could copy it and call it NewerStroke or something like that :wink:

**Comment by ubruhin** [comment]
> if you prefer I can adjust the lower Y coordinate as suggested.

Yeah I would really prefer it ;)

> By converting it we have already kind of forked it.

We only changed the file format, but we didn't modify the font itself. But OK let's modify it, we could still revert all changes and move them to a new font once we need it.

Btw, you should increment the font's version number to make the revisions distinguishable.

**Comment by dbrgn** [comment]
@ubruhin fixed! new version:

https://fontobene.dbrgn.ch/pathvis/#init=3,-1.5;2.57,-1.5;1.71,-1.07;1.29,-.21;1.29,2.46;.86,3.32;0,3.75;.86,4.18;1.29,5.04;1.29,7.71;1.71,8.57;2.57,9;3,9
https://fontobene.dbrgn.ch/pathvis/#init=3,-3.43;2.57,-3.43;1.71,-3;1.29,-2.14;1.29,2.14;.86,3;0,3.43;.86,3.86;1.29,4.71;1.29,9;1.71,9.86;2.57,10.29;3,10.29

**Review by ubruhin — APPROVED** [review]
:+1:

**Pull request merged**
